[project]
name = "mcp-fastapi"
version = "0.1.0"
description = "MCP FastAPI Tools"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.8",
    "loguru>=0.7.3",
    "pydantic-settings>=2.7.1",
    "uvicorn>=0.34.0",
]
